# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2.1

commands:
  checkout_and_restore_cache:
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

executors:
  node:
    docker:
      - image: circleci/node:12.8.0

jobs:
  install:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: npm run setup
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./acme.sh
  lint:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: npm run prettier:write
      - persist_to_workspace:
          root: ~/
          paths:
            - build/*
  test:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: npm run test
  build:
    executor: node
    steps:
      - checkout_and_restore_cache
      - run: npm run build
      # working_directory: ~/repo
      - persist_to_workspace:
          root: ~/
          paths:
            - build/*
  deploy:
      executor: node
      steps:
        - add_ssh_keys:
            fingerprints:
            - "SHA256:vNQhUA1Pu0/mCPSWwZ623uUtmljAksV9B0zUg/DWMC0 ledavid64@gmail.com"
        - checkout_and_restore_cache
        - attach_workspace:
            at: ~/project
        - run:
            name: Deploy Over SSH 🚀
            command: ssh dev@167.71.153.58 "git pull master"
        - run: echo myProxy has been succesfully deployed 🎉

workflows:
  version: 2
  integration:
    jobs:
      - install
      - build:
          requires:
            - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only: master